=== laoniutoushx/Venus/WebService/03_xml/src/main/java/com/haruhi/xml/classroom.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT classroom (claName, grade, students)>
<!ATTLIST classroom id ID #REQUIRED>
<!ELEMENT claName (#PCDATA)>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT students (student+)>
<!ELEMENT student (id, stuName, password, age)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT stuName (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT age (#PCDATA)>

=== laoniutoushx/Venus/WebService/03_xml/src/main/java/com/haruhi/xml/classroom.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE classroom SYSTEM "classroom.dtd">
<classroom id="cl1">
    <claName>一班</claName>
    <grade>三年级</grade>
    <students>
        <student>
            <id>s1</id>
            <stuName>凉宫</stuName>
            <password>000</password>
            <age>16</age>
        </student>
    </students>
</classroom>
